CDCatalogue/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Concrete;
using Domain.Models;
using Newtonsoft.Json;

namespace CDCatalogue.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IUnitOfWork _uow;

        public AlbumsController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Albums
        public ActionResult Index()
        {
            return View(_uow.AlbumRepository.GetAllAlbums());
        }

        public string GetAllAlbums()
        {
            var albums = _uow.AlbumRepository.GetAllAlbums();

            var albumsJson = JsonConvert.SerializeObject(albums, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return albumsJson;
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = _uow.AlbumRepository.GetAlbumById((int) id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return PartialView(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create([Bind(Include = "Id,Artist,Title,Genre,Year")] Album album)
        {
            if (ModelState.IsValid)
            {
                _uow.AlbumRepository.AddNewAlbum(album);
                return Json(true);
            }

            return Json(false);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = _uow.AlbumRepository.GetAlbumById((int)id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return PartialView(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Edit([Bind(Include = "Id,Artist,Title,Genre,Year")] Album album)
        {
            if (ModelState.IsValid)
            {
                _uow.AlbumRepository.EditAlbum(album);
                return Json(true);
            }
            return Json(false);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = _uow.AlbumRepository.GetAlbumById((int)id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return PartialView(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(int id)
        {
            try
            {
                Album album = _uow.AlbumRepository.GetAlbumById(id);
                _uow.AlbumRepository.RemoveAlbum(album);
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public ActionResult AddSong(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Album album = _uow.AlbumRepository.GetAlbumById((int)id);

            Song song = new Song();
            song.Album = album;

            if (album == null)
            {
                return HttpNotFound();
            }
            return PartialView(song);
        }

        [HttpPost]
        public JsonResult AddSong(Song model)
        {
            if (ModelState.IsValid)
            {
                var album = _uow.AlbumRepository.GetAlbumById(model.AlbumId);

                model.Album = album;

                if(_uow.AlbumRepository.AddSong(model))
                    return Json(true);
            }

            return Json(false);
        }
    }
}

CDCatalogue/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Models;

namespace CDCatalogue.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext _db = ApplicationDbContext.Create();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CDCatalogue/Views/Albums/AddSong.cshtml
@model Domain.Models.Song


@using (Html.BeginForm("AddSong", "Albums", FormMethod.Post, new { @id = "addSongForm" })) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.HiddenFor(model => model.Album.Id)

        <div>
            <p id="addedInfo"></p>
        </div>

        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @*<div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Song" class="btn btn-default" id="addNewSongBtn" onclick="return false;" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script>
    $('#addNewSongBtn').click(function () {
        var info = {
            AlbumId: $('#Album_Id').val(),
            Title: $('#Title').val()
        };
        $.ajax({
            url: 'Albums/AddSong',
            type: 'POST',
            data: JSON.stringify(info),
            contentType: 'application/json; charset=utf-8',
            success: function (msg) {
                console.log(msg);
                console.log(info);
                if(msg == 'true')
                $('#addedInfo').text("Song added successfully").fadeIn(2000).fadeOut(2000);
                $('#Title').val('');
            },
            error: function (msg) {
                console.log(msg);
            }
        });
    });
</script>

CDCatalogue/Views/Albums/Create.cshtml
@model Domain.Models.Album

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "Albums", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div>
            <p id="addedInfo"></p>
        </div>

        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Artist, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Genre, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new {htmlAttributes = new {@class = "form-control", @Value = 1900}})
                @Html.ValidationMessageFor(model => model.Year, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="addAlbumBtn" onclick="return false;"/>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $('#addAlbumBtn').click(function () {
        var info = {
            __RequestVerificationToken: $('#__RequestVerificationToken').val(),
            Artist: $('#Artist').val(),
            Title: $('#Title').val(),
            Genre: $('#Genre').val(),
            Year: $('#Year').val()
        };
        $.ajax({
            url: 'Albums/Create',
            type: 'POST',
            data: JSON.stringify(info),
            contentType: 'application/json; charset=utf-8',
            success: function (msg) {
                console.log(msg);
                $('#addedInfo').text("Album created successfully").fadeIn(2000).fadeOut(2000);
                refreshTable();
                location.reload();
            },
            error: function (msg) {
                console.log(msg);
            }
        });
    });

    function refreshTable() {
        $('#mainTable > tbody').empty();

        var jsondata;

        $.get('Albums/GetAllAlbums', function(data) {
            jsondata = jQuery.parseJSON(data);
            console.log(jsondata);

            $.each(jsondata, function (index, element) {
                $('table#mainTable TBODY').append('<tr><td>' + element.Artist + '</td><td>' + element.Title + '</td><td>' + element.Genre + '</td><td>' + element.Year + '</td><td>' +
                    '<a class="editBtn" href="/Albums/Edit/' + element.Id + '">Edit</a> | ' + 
                    '<a class="detailsBtn" href="/Albums/Details/' + element.Id + '">Details</a> | ' + 
                    '<a class="delBtn" href="/Albums/Delete/' + element.Id + '">Delete</a> | ' + 
                    '<a class="addSongBtn" href="/Albums/AddSong/' + element.Id + '">Add Songs</a>' + '</td></tr>');
            });
        });
    }
</script>

CDCatalogue/Views/Albums/Delete.cshtml
@model Domain.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h3 align="center">Are you sure you want to delete this album?</h3>
<hr/>
<div>

    @Html.HiddenFor(model => model.Id)

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Yes" class="btn btn-default" id="deleteAlbumBtn" onclick="return false;"/>
        </div>
    }
</div>

<script>
    $('#deleteAlbumBtn').click(function () {
        var info = {
            Id: $('#Id').val()
        };
        $.ajax({
            url: 'Albums/Delete',
            type: 'POST',
            data: JSON.stringify(info),
            contentType: 'application/json; charset=utf-8',
            success: function (msg) {
                console.log(msg);
                $('#addedInfo').text("Album deleted successfully").fadeIn(2000).fadeOut(2000);
                refreshTable();
                location.reload();
                $('#modal-manipulation').modal('hide');
            },
            error: function (msg) {
                $('#addedInfo').text(msg).fadeIn(2000).fadeOut(2000);
                console.log(msg);
            }
        });
    });

    function refreshTable() {
        $('#mainTable > tbody').empty();

        var jsondata;

        $.get('Albums/GetAllAlbums', function (data) {
            jsondata = jQuery.parseJSON(data);
            console.log(jsondata);

            $.each(jsondata, function (index, element) {
                $('table#mainTable TBODY').append('<tr><td>' + element.Artist + '</td><td>' + element.Title + '</td><td>' + element.Genre + '</td><td>' + element.Year + '</td><td>' +
                    '<a class="editBtn" href="/Albums/Edit/' + element.Id + '">Edit</a> | ' +
                    '<a class="detailsBtn" href="/Albums/Details/' + element.Id + '">Details</a> | ' +
                    '<a class="delBtn" href="/Albums/Delete/' + element.Id + '">Delete</a> | ' +
                    '<a class="addSongBtn" href="/Albums/AddSong/' + element.Id + '">Add Songs</a>' + '</td></tr>');
            });
        });
    }
</script>

CDCatalogue/Views/Albums/Details.cshtml
@model Domain.Models.Album

@{
    ViewBag.Title = "Details";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayName("Songs in album")
        </dt>

        @foreach (var song in Model.Songs)
        {
            <dd>
                <li>@song.Title</li>
            </dd>
        }
    </dl>
</div>

CDCatalogue/Views/Albums/Edit.cshtml
@model Domain.Models.Album

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div>
            <p id="addedInfo"></p>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="editAlbumBtn" onclick="return false;" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $('#editAlbumBtn').click(function () {
        var info = {
            __RequestVerificationToken: $('#__RequestVerificationToken').val(),
            Id: $('#Id').val(),
            Artist: $('#Artist').val(),
            Title: $('#Title').val(),
            Genre: $('#Genre').val(),
            Year: $('#Year').val()
        };
        $.ajax({
            url: 'Albums/Edit',
            type: 'POST',
            data: JSON.stringify(info),
            contentType: 'application/json; charset=utf-8',
            success: function (msg) {
                console.log(msg);
                refreshTable();
                location.reload();
                $('#addedInfo').text("Album edited successfully").fadeIn(2000).fadeOut(2000);
                $('#modal-manipulation').modal('hide');
            },
            error: function (msg) {
                console.log(msg);
            }
        });
    });

    function refreshTable() {
        $('#mainTable > tbody').empty();

        var jsondata;

        $.get('Albums/GetAllAlbums', function (data) {
            jsondata = jQuery.parseJSON(data);
            console.log(jsondata);

            $.each(jsondata, function (index, element) {
                $('table#mainTable TBODY').append('<tr><td>' + element.Artist + '</td><td>' + element.Title + '</td><td>' + element.Genre + '</td><td>' + element.Year + '</td><td>' +
                    '<a class="editBtn" href="/Albums/Edit/' + element.Id + '">Edit</a> | ' +
                    '<a class="detailsBtn" href="/Albums/Details/' + element.Id + '">Details</a> | ' +
                    '<a class="delBtn" href="/Albums/Delete/' + element.Id + '">Delete</a> | ' +
                    '<a class="addSongBtn" href="/Albums/AddSong/' + element.Id + '">Add Songs</a>' + '</td></tr>');
            });
        });
    }
</script>

CDCatalogue/Views/Albums/Index.cshtml
@model IEnumerable<Domain.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Album list</h2>

<p>
    <a class="btn btn-primary" id="createNewBtn">Add New Album</a>
</p>
<table class="table" id="mainTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Artist)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "editBtn" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "detailsBtn" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "delBtn" }) |
                    @Html.ActionLink("Add Songs", "AddSong", new { id = item.Id }, new { @class = "addSongBtn" })
                </td>
            </tr>
        }
    </tbody>

</table>

<div class="modal fade" id="modal-addnew">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Create new album</h4>
            </div>
            <div class="modal-body" id="modal-body-addnew">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-manipulation">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Album Actions</h4>
            </div>
            <div class="modal-body" id="modal-body-manipulation">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

CDCatalogue/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CDCatalogue/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CDCatalogue/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CDCatalogue/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                    <li>@Html.ActionLink("Albums Controller", "Index", "Albums")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


<script>
    $(document).ready(function() {
        $('#createNewBtn').click(function() {
            $('#modal-body-addnew').load('@Url.Action("Create", "Albums")');
            $('#modal-addnew').modal();
            return false;
        });

        $('.addSongBtn').click(function () {
            var adres = $(this).attr('href');
            $('#modal-body-manipulation').load(adres);
            $('#modal-manipulation').modal();
            return false;
        });

        $('.editBtn').click(function () {
            var adres = $(this).attr('href');
            $('#modal-body-manipulation').load(adres);
            $('#modal-manipulation').modal();
            return false;
        });

        $('.detailsBtn').click(function () {
            var adres = $(this).attr('href');
            $('#modal-body-manipulation').load(adres);
            $('#modal-manipulation').modal();
            return false;
        });

        $('.delBtn').click(function () {
            var adres = $(this).attr('href');
            $('#modal-body-manipulation').load(adres);
            $('#modal-manipulation').modal();
            return false;
        });
    });
</script>

</body>
</html>